import { useState } from "react";
import { useQuery, keepPreviousData } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { Question, Subject } from "../lib/types";

interface QuestionsResponse {
  total: number;
  page: number;
  pageSize: number;
  questions: Question[];
}

export function QuestionBankPage(): JSX.Element {
  const { data: subjectsData } = useQuery({
    queryKey: ["subjects"],
    queryFn: () => api<{ subjects: Subject[] }>("/api/syllabus/subjects"),
  });
  const subjects = subjectsData?.subjects ?? [];

  const [subjectId, setSubjectId] = useState<string | null>(null);
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery({
    queryKey: ["questions", subjectId, page],
    queryFn: () => {
      const params = new URLSearchParams({ page: String(page), pageSize: "10" });
      if (subjectId) params.set("subjectId", subjectId);
      return api<QuestionsResponse>(`/api/questions?${params.toString()}`);
    },
    placeholderData: keepPreviousData,
  });

  const totalPages = data ? Math.max(1, Math.ceil(data.total / data.pageSize)) : 1;

  function selectSubject(id: string | null): void {
    setSubjectId(id);
    setPage(1);
  }

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">Question bank</h1>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted">
          Real NEET past-year questions with verified answer keys. Attempt one, then reveal the
          answer. Detailed explanations are generated by the content agent (arrives with M3).
        </p>
      </header>

      <div className="flex flex-wrap gap-2">
        <FilterChip label="All" active={subjectId === null} onClick={() => selectSubject(null)} />
        {subjects.map((s) => (
          <FilterChip
            key={s.id}
            label={s.name}
            active={subjectId === s.id}
            onClick={() => selectSubject(s.id)}
          />
        ))}
      </div>

      {isLoading && !data ? (
        <p className="font-mono text-sm text-muted">loading questions…</p>
      ) : (
        <>
          <p className="font-mono text-xs text-muted">
            {data?.total ?? 0} questions{subjectId ? " in this subject" : ""}
          </p>
          <ul className="space-y-4">
            {data?.questions.map((q, i) => (
              <QuestionCard key={q.id} q={q} index={(page - 1) * (data?.pageSize ?? 10) + i + 1} />
            ))}
          </ul>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-4 pt-2">
              <button
                disabled={page <= 1}
                onClick={() => setPage((p) => p - 1)}
                className="rounded-md border border-hairline px-3 py-1.5 text-sm text-muted transition-colors duration-200 hover:text-ink disabled:opacity-40"
              >
                ← Prev
              </button>
              <span className="font-mono text-xs text-muted">
                {page} / {totalPages}
              </span>
              <button
                disabled={page >= totalPages}
                onClick={() => setPage((p) => p + 1)}
                className="rounded-md border border-hairline px-3 py-1.5 text-sm text-muted transition-colors duration-200 hover:text-ink disabled:opacity-40"
              >
                Next →
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function FilterChip({
  label,
  active,
  onClick,
}: {
  label: string;
  active: boolean;
  onClick: () => void;
}): JSX.Element {
  return (
    <button
      onClick={onClick}
      className={`rounded-lg border px-4 py-2 text-sm transition-colors duration-200 ${
        active
          ? "border-accent bg-accent/10 text-ink"
          : "border-hairline text-muted hover:border-muted hover:text-ink"
      }`}
    >
      {label}
    </button>
  );
}

function QuestionCard({ q, index }: { q: Question; index: number }): JSX.Element {
  const [chosen, setChosen] = useState<number | null>(null);
  const revealed = chosen !== null;

  return (
    <li className="rounded-xl border border-hairline bg-surface p-5">
      <div className="mb-3 flex items-center gap-3">
        <span className="font-mono text-xs text-muted">#{index}</span>
        <span className="rounded border border-hairline px-1.5 py-0.5 font-mono text-[10px] uppercase text-muted">
          {q.subject.name}
        </span>
        <span className="rounded border border-hairline px-1.5 py-0.5 font-mono text-[10px] uppercase text-muted">
          {q.source}
        </span>
      </div>

      {/* PYQ stems are plain text; KaTeX/markdown rendering lands with
          agent-generated content in M6. Preserve intra-stem spacing. */}
      <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink">{q.stem}</p>

      <ul className="mt-4 space-y-2">
        {q.options.map((opt, i) => {
          const isCorrect = i === q.correctIndex;
          const isChosen = i === chosen;
          let cls = "border-hairline hover:border-muted";
          if (revealed && isCorrect) cls = "border-accent bg-accent/10";
          else if (revealed && isChosen && !isCorrect) cls = "border-danger bg-danger/10";
          return (
            <li key={i}>
              <button
                disabled={revealed}
                onClick={() => setChosen(i)}
                className={`flex w-full items-start gap-3 rounded-lg border px-4 py-2.5 text-left text-sm transition-colors duration-200 ${cls} disabled:cursor-default`}
              >
                <span className="font-mono text-xs text-muted">{"1234"[i]}</span>
                <span className="flex-1">{opt}</span>
                {revealed && isCorrect && <span className="text-accent">✓</span>}
                {revealed && isChosen && !isCorrect && <span className="text-danger">✗</span>}
              </button>
            </li>
          );
        })}
      </ul>

      {revealed && (
        <div className="mt-4 rounded-lg border border-hairline bg-bg/40 px-4 py-3 text-sm">
          {chosen === q.correctIndex ? (
            <p className="text-accent">Correct.</p>
          ) : (
            <p className="text-muted">
              Correct answer:{" "}
              <span className="text-accent">option {q.correctIndex + 1}</span>
            </p>
          )}
          {q.explanation ? (
            <p className="mt-1 leading-relaxed text-muted">{q.explanation}</p>
          ) : (
            <p className="mt-1 text-xs text-muted/70">
              Detailed explanation not generated yet (arrives with the M3 content agent).
            </p>
          )}
        </div>
      )}
    </li>
  );
}
